### ISSUE TITLE
Use srv record for LDAP server

### ISSUE THREAD

**Issue by devinmatte** [zthart/mizu#16]
Drink appears to currently pick `ipa01-nrh.csh.rit.edu` as it's ldap server. That server no longer exists after this weekend.
You should use the `csh.rit.edu` srv record to pick a ldap server to connect to.

Example of how csh_ldap does it https://github.com/liam-middlebrook/csh_ldap/blob/master/csh_ldap/__init__.py#L28-L32

**Comment by nickdepinet** [comment]
drink uses the latest(?) csh_ldap 2.2.0 with default init, so it looks like it's already doing that.

**Comment by devinmatte** [comment]
Gotcha, if so, close the issue. There was a line in `config.py` that lead me to believe drink was pointing at a specific ldap server

**Comment by hearthsinger** [comment]
Yeah at some point I believe that we were making a manual connection to LDAP in the admin panel since the abstraction in `csh_ldap` had really significant performance impacts, but a search for the `LDAP_URL` var only returns the line in config where it's set, and in the `users.py` module we're just pulling the connection object out from within the `csh_ldap` client and making a `search_s` call ourselves. The line was changed at some point from `ldaps://ldap.csh.rit.edu` to the `ipa01-nrh` address because someone told us to do that ([blame](https://github.com/zthart/mizu/blame/557e18dbf7d6c81a41b12fbba97574be46f03ab5/mizu/config.py#L18)), I don't remember exactly when we stopped using it.
